version: '3.5'

services:
  fuseki:
    image: stain/jena-fuseki:3.14.0
    volumes:
      - ./:/datasets
    ports:
      - 3030:3030
    environment:
      - TZ=Europe/Oslo
      - ADMIN_PASSWORD=pw123
      - FUSEKI_DATASET_1=APS
      - FUSEKI_DATASET_2=ET
    entrypoint: /bin/bash /datasets/scripts/custom_docker_entrypoint.sh

