PREFIX : <https://www.sdir.no/SDIR_Simulator#> 
PREFIX scope: <https://www.sdir.no/SDIR_Simulator/shapes/scope#> 
PREFIX unit: <http://qudt.org/vocab/unit/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX sh: <http://www.w3.org/ns/shacl#>

# Get all requirements based on radio area

SELECT DISTINCT *
WHERE {
  ?requirement a :Requirement ;
               sh:property ?scope .
  
  ?scope a :Scope ;
         sh:path :radioArea ;
         sh:hasValue ?radioArea .
  
  ?radioArea rdfs:label ?radioAreaLabel .
  FILTER(LANG(?radioAreaLabel) = 'no')
}