PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX : <https://www.sdir.no/SDIR_Simulator#>
PREFIX course: <https://www.sdir.no/SDIR_Simulator/shapes/course#>
PREFIX cert: <https://www.sdir.no/SDIR_Simulator/shapes/certificate#>
PREFIX sh: <http://www.w3.org/ns/shacl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX req: <http://www.sidr.no/SDIR_Simulator/requirements#>

SELECT DISTINCT ?educationLabel
WHERE {
  ?nodeShape sh:targetClass ?certClass .
  FILTER(REGEX(STR(?certClass), "D3B0"))

  # When there is more than one education requirement
  OPTIONAL {
  	?nodeShape sh:or/rdf:rest*/rdf:first ?orListItem .
    ?orListItem sh:path :requiresEducation ;
                sh:hasValue ?education .
    ?education rdfs:label ?educationLabel .
    FILTER(LANG(?educationLabel) = 'no')
  }
  
  # When there is one education requirement
  OPTIONAL {
  	?nodeShape sh:property ?propertyShape .
    ?propertyShape sh:path :requiresEducation ;
                   sh:hasValue ?education .
    ?education rdfs:label ?educationLabel .
    FILTER(LANG(?educationLabel) = 'no')
  }
}